### ISSUE TITLE
Picture width not equals length!

### ISSUE THREAD

**Issue by shufxkup** [nemanja-m/gaps#17]
Is there a way to deal with the difference in length and width at present??

**Comment by nemanja-m** [comment]
Hi @shufxkup,

Currently, pictures with `width != height` are supported _only if_ width and height are divisible by puzzle piece size in pixels. 

For example, for the piece size of 64 px:

- The picture with 512x640 px can be solved as 512 / 64 = 8 and 640 / 64 = 10
- The picture with 512x600 px can't be correctly divided to the pieces of 64px because 600 MOD 64 != 0

Although, puzzle pieces must be square.

**Comment by shufxkup** [comment]
Thanks for introduction, Your program helped a lot ,Looking forward to better code
